#!/bin/sh
# Output GIMPLE tree output
g++ main.cpp -fdump-tree-gimple -o example1

# Output RTL
g++ main.cpp -fdump-rtl-expand -o example5

# Output SSA
g++ main.cpp -fdump-tree-ssa -o example6

# Output Abstract Syntax Tree (AST) as a graph
g++ -fdump-tree-all-graph main.cpp -o example7

# Plot them
dot -Tpng main.cpp.011t.cfg.dot -o cfg.png
dot -Tpng main.cpp.012t.ompexp.dot -o ompexp.png
dot -Tpng main.cpp.013t.printf-return-value1.dot -o retvalue.png
dot -Tpng main.cpp.019t.fixup_cfg1.dot -o main4.png

dot -Tpng main.cpp.020t.ssa.dot -o SSA.png
dot -Tpng main.cpp.027t.fixup_cfg3.dot -o main6.png
dot -Tpng main.cpp.028t.inline_param1.dot -o main7.png
dot -Tpng main.cpp.029t.einline.dot -o main8.png
dot -Tpng main.cpp.049t.release_ssa.dot -o main9.png
dot -Tpng main.cpp.050t.inline_param2.dot -o main1.png
dot -Tpng main.cpp.086t.fixup_cfg4.dot -o main2.png
dot -Tpng main.cpp.218t.veclower.dot -o main3.png
dot -Tpng main.cpp.219t.cplxlower0.dot -o main4.png
dot -Tpng main.cpp.225t.resx.dot -o main5.png
dot -Tpng main.cpp.227t.optimized.dot -o optimised.png
