#!/bin/sh
g++ main.cpp RandomMinute.cpp SomeClass.cpp FakeRandomMinute.cpp FakeSomeClassValue.cpp -o example
./example

g++ -Wl,--wrap=_ZN9SomeClass5ValueEv,--wrap=_Z16RandomMinute_Getv main.cpp RandomMinute.cpp SomeClass.cpp FakeRandomMinute.cpp FakeSomeClassValue.cpp -o example2
./example2

clang++-10 -stdlib=libc++ -std=c++17 main.cpp RandomMinute.cpp SomeClass.cpp FakeRandomMinute.cpp FakeSomeClassValue.cpp -o example3
./example3

clang++-6.0 -stdlib=libc++ -std=c++17 -Wl,--wrap=_Z16RandomMinute_Getv main.cpp RandomMinute.cpp SomeClass.cpp FakeRandomMinute.cpp FakeSomeClassValue.cpp -o example4
./example4

clang++-6.0 -stdlib=libc++ -std=c++17 -Wl,--wrap=_ZN9SomeClass5ValueEv main.cpp RandomMinute.cpp SomeClass.cpp FakeRandomMinute.cpp FakeSomeClassValue.cpp -o example5
./example5
